spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JulianMorgant/config-server-repo.git
          search-paths: microservice-mine



#  profiles:
#    active: @spring.profiles.active@

server:
  port: 9101


management:
  endpoints:
    web:
      exposure:
        include: "*"

